import { createFileRoute } from '@tanstack/react-router';
import { AdminTopBar } from '~/components/admin/AdminTopBar';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { ChevronLeft, ChevronRight, Sparkles, Plus, X, AlertTriangle } from 'lucide-react';
import toast from 'react-hot-toast';
import { useQuery } from '@tanstack/react-query';
import { useTRPC } from '~/trpc/react';

export const Route = createFileRoute('/admin/create/')({
  component: CreateMarket,
});

type FormData = {
  sport: string;
  league: string;
  eventName: string;
  eventDate: string;
  eventTime: string;
  timezone: string;
  venue: string;
  region: string;
  marketType: 'binary' | 'two-outcomes' | 'multiple';
  outcomeA: string;
  outcomeB: string;
  additionalOutcomes: string[];
  includeDraw: boolean;
  oddsA: string;
  oddsB: string;
  resolutionType: 'automatic' | 'manual';
  bettingCloses: 'event-start' | 'custom';
  customCloseTime: string;
  description: string;
  resolutionRules: string;
  tags: string[];
};

function CreateMarket() {
  const trpc = useTRPC();
  const azuroList = useQuery({
    ...trpc.getAzuroMarkets.queryOptions({}),
    staleTime: 60_000,
  });

  const [currentStep, setCurrentStep] = useState(1);
  const [aiAssist, setAiAssist] = useState(false);
  const [aiPrompt, setAiPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  const { register, handleSubmit, formState: { errors }, setValue, watch } = useForm<FormData>({
    defaultValues: {
      marketType: 'two-outcomes',
      resolutionType: 'automatic',
      bettingCloses: 'event-start',
      timezone: 'UTC',
      region: 'Europe',
      includeDraw: false,
      additionalOutcomes: [],
      tags: [],
    },
  });

  const marketType = watch('marketType');
  const includeDraw = watch('includeDraw');

  const openMarketsCount = (azuroList.data?.markets ?? []).filter(
    (m) => m.status === 'upcoming' || m.status === 'ending-soon' || m.status === 'live',
  ).length;
  const maxMarkets = 15;
  const isAtLimit = openMarketsCount >= maxMarkets;

  const handleAIGenerate = async () => {
    setIsGenerating(true);
    
    // Simulate AI generation
    await new Promise(resolve => setTimeout(resolve, 1500));
    
    // Pre-fill form with mock data
    setValue('sport', 'Football');
    setValue('league', 'UEFA Champions League');
    setValue('eventName', 'Real Madrid vs FC Barcelona');
    setValue('eventDate', '2025-05-14');
    setValue('eventTime', '20:00');
    setValue('timezone', 'CET');
    setValue('venue', 'Santiago Bernabéu, Madrid');
    setValue('region', 'Europe');
    setValue('outcomeA', 'Real Madrid Win');
    setValue('outcomeB', 'Barcelona Win');
    setValue('includeDraw', true);
    setValue('description', 'UEFA Champions League semifinal match between Real Madrid and FC Barcelona at Santiago Bernabéu.');
    setValue('resolutionRules', 'Resolves based on 90-minute result. Extra time and penalties not counted.');
    
    setIsGenerating(false);
    toast.success('Form auto-generated by AI');
  };

  const onSubmit = (data: FormData) => {
    console.log('Market data:', data);
    toast.success('Market #1043 published successfully');
  };

  const nextStep = () => {
    if (currentStep < 4) setCurrentStep(currentStep + 1);
  };

  const prevStep = () => {
    if (currentStep > 1) setCurrentStep(currentStep - 1);
  };

  return (
    <div className="min-h-screen">
      <AdminTopBar title="Create Market" breadcrumbs={['Markets']} />
      
      <div className="p-6">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <div className="mb-8">
            <h1 className="text-2xl font-syne font-bold mb-2">Create New Market</h1>
            <p className="text-gray-400">Markets created here go live immediately on Predictio</p>
          </div>

          {/* Market Limit Counter */}
          <div className="mb-6 flex items-center justify-between p-4 bg-white/5 border border-white/10 rounded-xl">
            <div className="flex items-center gap-3">
              <span className="text-sm text-gray-400">Open markets:</span>
              <span className={`text-2xl font-bold font-mono ${
                openMarketsCount >= maxMarkets ? 'text-red-500' : 
                openMarketsCount >= maxMarkets * 0.8 ? 'text-yellow-500' : 
                'text-brand-green'
              }`}>
                {openMarketsCount} / {maxMarkets}
              </span>
            </div>
            {openMarketsCount >= maxMarkets * 0.8 && (
              <span className="text-xs text-gray-400">
                {openMarketsCount >= maxMarkets 
                  ? 'Market limit reached' 
                  : `${maxMarkets - openMarketsCount} slots remaining`}
              </span>
            )}
          </div>

          {/* Market Limit Warning */}
          {isAtLimit && (
            <div className="mb-6 p-6 bg-red-500/10 border border-red-500/30 rounded-xl animate-fade-in">
              <div className="flex items-start gap-3">
                <AlertTriangle className="w-6 h-6 text-red-500 flex-shrink-0 mt-1" />
                <div>
                  <h3 className="font-syne font-bold text-lg text-red-500 mb-2">
                    ⚠ Market limit reached
                  </h3>
                  <p className="text-gray-300 mb-3">
                    You have {openMarketsCount} open markets. Close or resolve existing markets before creating new ones.
                  </p>
                  <p className="text-sm text-gray-400">
                    <strong>Tip:</strong> Focus liquidity on fewer, deeper markets for better UX.
                  </p>
                </div>
              </div>
            </div>
          )}

          {/* AI Assist Toggle */}
          <div className="mb-6 p-4 bg-gradient-to-r from-purple-500/10 to-pink-500/10 border border-purple-500/30 rounded-xl">
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-2">
                <Sparkles className="text-purple-400" size={20} />
                <span className="font-syne font-bold">AI Assist</span>
              </div>
              <button
                onClick={() => setAiAssist(!aiAssist)}
                className={`
                  relative w-12 h-6 rounded-full transition-colors
                  ${aiAssist ? 'bg-purple-500' : 'bg-white/20'}
                `}
              >
                <div
                  className={`
                    absolute top-1 w-4 h-4 bg-white rounded-full transition-transform
                    ${aiAssist ? 'translate-x-7' : 'translate-x-1'}
                  `}
                />
              </button>
            </div>
            
            {aiAssist && (
              <div className="space-y-3 animate-slide-down">
                <input
                  type="text"
                  placeholder="Describe the event in natural language..."
                  value={aiPrompt}
                  onChange={(e) => setAiPrompt(e.target.value)}
                  className="w-full px-4 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:border-purple-500 transition-colors"
                />
                <button
                  onClick={handleAIGenerate}
                  disabled={isGenerating || !aiPrompt}
                  className="px-4 py-2 bg-purple-500 hover:bg-purple-600 disabled:bg-purple-500/50 text-white rounded-lg text-sm font-medium transition-colors"
                >
                  {isGenerating ? 'Generating...' : 'Generate →'}
                </button>
              </div>
            )}
          </div>

          {/* Progress Steps */}
          <div className="flex items-center justify-between mb-8">
            {[1, 2, 3, 4].map((step) => (
              <div key={step} className="flex items-center flex-1">
                <div
                  className={`
                    w-10 h-10 rounded-full flex items-center justify-center font-mono font-bold transition-colors
                    ${currentStep >= step
                      ? 'bg-brand-green text-black'
                      : 'bg-white/5 text-gray-500'
                    }
                  `}
                >
                  {step}
                </div>
                {step < 4 && (
                  <div
                    className={`
                      flex-1 h-0.5 mx-2 transition-colors
                      ${currentStep > step ? 'bg-brand-green' : 'bg-white/10'}
                    `}
                  />
                )}
              </div>
            ))}
          </div>

          {/* Form */}
          <form onSubmit={handleSubmit(onSubmit)}>
            <div className="bg-white/5 border border-white/10 rounded-xl p-8 mb-6">
              {/* Step 1: Sport & Event */}
              {currentStep === 1 && (
                <div className="space-y-6 animate-fade-in">
                  <h2 className="text-xl font-syne font-bold mb-6">Sport & Event (1/4)</h2>
                  
                  <div className="grid grid-cols-2 gap-6">
                    <div>
                      <label className="block text-sm font-medium text-gray-300 mb-2">
                        Sport *
                      </label>
                      <select
                        {...register('sport', { required: 'Sport is required' })}
                        className="w-full px-4 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:border-brand-green transition-colors"
                      >
                        <option value="">Select sport...</option>
                        <option value="Football">⚽ Football</option>
                        <option value="Basketball">🏀 Basketball</option>
                        <option value="Tennis">🎾 Tennis</option>
                        <option value="MMA">🥊 MMA</option>
                        <option value="Cricket">🏏 Cricket</option>
                      </select>
                      {errors.sport && (
                        <p className="mt-1 text-sm text-red-500">{errors.sport.message}</p>
                      )}
                    </div>

                    <div>
                      <label className="block text-sm font-medium text-gray-300 mb-2">
                        League / Competition *
                      </label>
                      <input
                        {...register('league', { required: 'League is required' })}
                        className="w-full px-4 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:border-brand-green transition-colors"
                        placeholder="e.g. UEFA Champions League"
                      />
                      {errors.league && (
                        <p className="mt-1 text-sm text-red-500">{errors.league.message}</p>
                      )}
                    </div>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">
                      Event Name *
                    </label>
                    <input
                      {...register('eventName', { required: 'Event name is required' })}
                      className="w-full px-4 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:border-brand-green transition-colors"
                      placeholder="e.g. Real Madrid vs FC Barcelona"
                    />
                    {errors.eventName && (
                      <p className="mt-1 text-sm text-red-500">{errors.eventName.message}</p>
                    )}
                  </div>

                  <div className="grid grid-cols-3 gap-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-300 mb-2">
                        Event Date *
                      </label>
                      <input
                        type="date"
                        {...register('eventDate', { required: 'Date is required' })}
                        className="w-full px-4 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:border-brand-green transition-colors"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-300 mb-2">
                        Event Time *
                      </label>
                      <input
                        type="time"
                        {...register('eventTime', { required: 'Time is required' })}
                        className="w-full px-4 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:border-brand-green transition-colors"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-300 mb-2">
                        Timezone
                      </label>
                      <select
                        {...register('timezone')}
                        className="w-full px-4 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:border-brand-green transition-colors"
                      >
                        <option value="UTC">UTC</option>
                        <option value="CET">CET</option>
                        <option value="EST">EST</option>
                        <option value="PST">PST</option>
                      </select>
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-6">
                    <div>
                      <label className="block text-sm font-medium text-gray-300 mb-2">
                        Venue (optional)
                      </label>
                      <input
                        {...register('venue')}
                        className="w-full px-4 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:border-brand-green transition-colors"
                        placeholder="e.g. Santiago Bernabéu, Madrid"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-300 mb-2">
                        Region
                      </label>
                      <select
                        {...register('region')}
                        className="w-full px-4 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white focus:outline-none focus:border-brand-green transition-colors"
                      >
                        <option value="Europe">Europe</option>
                        <option value="Americas">Americas</option>
                        <option value="Asia-Pacific">Asia-Pacific</option>
                        <option value="Africa">Africa</option>
                        <option value="Middle East">Middle East</option>
                      </select>
                    </div>
                  </div>
                </div>
              )}

              {/* Step 2: Market Type & Outcomes */}
              {currentStep === 2 && (
                <div className="space-y-6 animate-fade-in">
                  <h2 className="text-xl font-syne font-bold mb-6">Market Type & Outcomes (2/4)</h2>
                  
                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-3">
                      Market Type *
                    </label>
                    <div className="space-y-2">
                      <label className="flex items-center gap-3 p-3 bg-white/5 border border-white/10 rounded-lg cursor-pointer hover:border-brand-green/50 transition-colors">
                        <input
                          type="radio"
                          value="two-outcomes"
                          {...register('marketType')}
                          className="text-brand-green"
                        />
                        <span>Two Outcomes (Team A / Team B)</span>
                        <span className="ml-auto text-xs text-gray-500">← default for sports</span>
                      </label>
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-6">
                    <div>
                      <label className="block text-sm font-medium text-gray-300 mb-2">
                        Outcome A *
                      </label>
                      <input
                        {...register('outcomeA', { required: 'Outcome A is required' })}
                        className="w-full px-4 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:border-brand-green transition-colors"
                        placeholder="e.g. Real Madrid Win"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-300 mb-2">
                        Outcome B *
                      </label>
                      <input
                        {...register('outcomeB', { required: 'Outcome B is required' })}
                        className="w-full px-4 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:border-brand-green transition-colors"
                        placeholder="e.g. Barcelona Win"
                      />
                    </div>
                  </div>

                  <label className="flex items-center gap-3 p-3 bg-white/5 border border-white/10 rounded-lg cursor-pointer">
                    <input
                      type="checkbox"
                      {...register('includeDraw')}
                      className="rounded text-brand-green"
                    />
                    <span className="text-sm">Include Draw option?</span>
                  </label>

                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">
                      Initial Odds (optional)
                    </label>
                    <div className="grid grid-cols-2 gap-4">
                      <input
                        {...register('oddsA')}
                        type="number"
                        step="0.01"
                        min="1"
                        max="10"
                        className="w-full px-4 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:border-brand-green transition-colors"
                        placeholder="Outcome A odds"
                      />
                      <input
                        {...register('oddsB')}
                        type="number"
                        step="0.01"
                        min="1"
                        max="10"
                        className="w-full px-4 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:border-brand-green transition-colors"
                        placeholder="Outcome B odds"
                      />
                    </div>
                    <p className="mt-2 text-xs text-gray-500">If empty, odds will be calculated automatically by Azuro</p>
                  </div>
                </div>
              )}

              {/* Step 3: Resolution Settings */}
              {currentStep === 3 && (
                <div className="space-y-6 animate-fade-in">
                  <h2 className="text-xl font-syne font-bold mb-6">Resolution Settings (3/4)</h2>
                  
                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-3">
                      Resolution Type *
                    </label>
                    <div className="space-y-2">
                      <label className="flex items-center gap-3 p-3 bg-white/5 border border-white/10 rounded-lg cursor-pointer hover:border-brand-green/50 transition-colors">
                        <input
                          type="radio"
                          value="automatic"
                          {...register('resolutionType')}
                          className="text-brand-green"
                        />
                        <span>Automatic (via Azuro Oracle)</span>
                        <span className="ml-auto text-xs text-green-500">← recommended</span>
                      </label>
                      <label className="flex items-center gap-3 p-3 bg-white/5 border border-white/10 rounded-lg cursor-pointer hover:border-brand-green/50 transition-colors">
                        <input
                          type="radio"
                          value="manual"
                          {...register('resolutionType')}
                          className="text-brand-green"
                        />
                        <span>Manual (admin resolves manually)</span>
                      </label>
                    </div>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">
                      Market Description *
                    </label>
                    <textarea
                      {...register('description', { required: 'Description is required', maxLength: 500 })}
                      rows={3}
                      maxLength={500}
                      className="w-full px-4 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:border-brand-green transition-colors resize-none"
                      placeholder="Describe the event and what users are predicting..."
                    />
                    <p className="mt-1 text-xs text-gray-500">Max 500 characters</p>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">
                      Resolution Rules *
                    </label>
                    <textarea
                      {...register('resolutionRules', { required: 'Resolution rules are required' })}
                      rows={3}
                      className="w-full px-4 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:border-brand-green transition-colors resize-none"
                      placeholder="e.g. Resolves based on 90-minute result. Extra time not counted."
                    />
                  </div>
                </div>
              )}

              {/* Step 4: Review & Publish */}
              {currentStep === 4 && (
                <div className="space-y-6 animate-fade-in">
                  <h2 className="text-xl font-syne font-bold mb-6">Review & Publish (4/4)</h2>
                  
                  <div className="bg-white/5 border border-white/10 rounded-lg p-6">
                    <h3 className="font-syne font-bold mb-4">Market Preview</h3>
                    <div className="space-y-3 text-sm">
                      <div className="flex justify-between">
                        <span className="text-gray-400">Sport:</span>
                        <span className="font-mono">{watch('sport') || '—'}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-gray-400">Event:</span>
                        <span className="font-mono">{watch('eventName') || '—'}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-gray-400">Outcomes:</span>
                        <span className="font-mono">
                          {watch('outcomeA')} / {watch('outcomeB')}
                          {includeDraw && ' / Draw'}
                        </span>
                      </div>
                    </div>
                  </div>

                  <div className="space-y-2">
                    <div className="flex items-center gap-2 text-sm">
                      <span className="text-green-500">✅</span>
                      <span>Event name complete</span>
                    </div>
                    <div className="flex items-center gap-2 text-sm">
                      <span className="text-green-500">✅</span>
                      <span>Outcomes defined</span>
                    </div>
                    <div className="flex items-center gap-2 text-sm">
                      <span className="text-green-500">✅</span>
                      <span>Resolution rules defined</span>
                    </div>
                  </div>
                </div>
              )}
            </div>

            {/* Navigation Buttons */}
            <div className="flex items-center justify-between">
              <button
                type="button"
                onClick={prevStep}
                disabled={currentStep === 1}
                className="flex items-center gap-2 px-6 py-3 bg-white/5 hover:bg-white/10 disabled:opacity-50 disabled:cursor-not-allowed text-white rounded-lg font-medium transition-colors"
              >
                <ChevronLeft size={20} />
                Previous
              </button>

              <div className="flex gap-3">
                {currentStep === 4 && (
                  <button
                    type="button"
                    className="px-6 py-3 bg-white/5 hover:bg-white/10 text-white rounded-lg font-medium transition-colors"
                  >
                    Save as Draft
                  </button>
                )}
                
                {currentStep < 4 ? (
                  <button
                    type="button"
                    onClick={nextStep}
                    className="flex items-center gap-2 px-6 py-3 bg-brand-green hover:bg-brand-green/90 text-black rounded-lg font-medium transition-colors"
                  >
                    Next
                    <ChevronRight size={20} />
                  </button>
                ) : (
                  <button
                    type="submit"
                    disabled={isAtLimit}
                    className="px-6 py-3 bg-brand-green hover:bg-brand-green/90 disabled:bg-gray-600 disabled:cursor-not-allowed disabled:opacity-50 text-black rounded-lg font-medium transition-colors"
                  >
                    {isAtLimit ? 'Market Limit Reached' : 'Publish Market'}
                  </button>
                )}
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}
